// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	article2 "github.com/johnwongx/webook/backend/internal/events/article"
	"github.com/johnwongx/webook/backend/internal/repository"
	"github.com/johnwongx/webook/backend/internal/repository/cache"
	"github.com/johnwongx/webook/backend/internal/repository/dao"
	"github.com/johnwongx/webook/backend/internal/repository/dao/article"
	"github.com/johnwongx/webook/backend/internal/service"
	"github.com/johnwongx/webook/backend/internal/web"
	"github.com/johnwongx/webook/backend/internal/web/jwt"
	"github.com/johnwongx/webook/backend/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	cmdable := ioc.InitRedis()
	limiter := ioc.InitRedisRateLimit(cmdable)
	jwtHandler := jwt.NewRedisJwtHandler(cmdable)
	logger := ioc.InitLogger()
	v := ioc.InitMiddlewares(limiter, jwtHandler, logger)
	db := ioc.InitDB(logger)
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewRedisUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository, logger)
	smsService := ioc.InitTencentSms(cmdable)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	codeService := service.NewCodeService(smsService, codeRepository)
	userHandler := web.NewUserHandler(userService, codeService, logger, jwtHandler)
	wechatService := ioc.InitWechatService(logger)
	wechatHandlerConfig := ioc.NewWechatHandlerConfig()
	oAuth2WechatHandler := web.NewWechatHandler(wechatService, userService, wechatHandlerConfig)
	articleDAO := article.NewGORMArticleDAO(db, logger)
	articleCache := cache.NewRedisArticleCache(cmdable)
	articleRepository := repository.NewArticleRepository(articleDAO, userRepository, articleCache, logger)
	articleService := service.NewArticleService(articleRepository, logger)
	interactiveDAO := dao.NewGORMInteractiveDAO(db, logger)
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository.NewInteractiveRepository(interactiveDAO, interactiveCache, logger)
	interactiveService := service.NewInteractiveService(interactiveRepository)
	client := ioc.InitKafka()
	syncProducer := ioc.NewSyncProducer(client)
	producer := article2.NewKafkaProducer(syncProducer)
	articleHandler := web.NewArticleHandler(articleService, interactiveService, logger, producer)
	engine := ioc.InitWebServer(v, userHandler, oAuth2WechatHandler, articleHandler)
	batchKafkaConsumer := article2.NewBatchKafkaConsumer(client, interactiveRepository, logger)
	v2 := ioc.NewConsumers(batchKafkaConsumer)
	app := &App{
		server:    engine,
		consumers: v2,
	}
	return app
}
